<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  new Promise((resolve, reject)=>{
    resolve();
    // reject('第一步错误');
  })
  .then(()=>{
    // console.log('登录成功');
    return new Promise((resolve, reject)=>{
      reject('登录失败');
    });
  })
  .then(()=>{
    console.log('是管理员');
  }/*, ()=>{ // 注意和下面统一捕获的冲突问题
    console.log('...')
  }*/)
  .then(()=>{
    console.log('拿到资源');
  }).catch((err)=>{ // 能捕获上面所有的then问题 // catch也能返回一个成功状态的Promise对象
    console.log(err);
  }).then(()=>{
    console.log('catch之后');
  });
</script>

</body>
</html>